### ISSUE TITLE
hose dose not work 

### ISSUE THREAD

**Issue by Gamediamond3757** [Nagol12344/python-test#5]
You wake up to find pitchforks and fire coming to your house
The vliiagers are shouting "DEATH TO THE WITCH"
"Oh no", you think "They know the witch is here"
What do you want to do?
Type 1 To try to trick the villagers to set fire to A diffrent house
Type 2 to try to set fire to them
Type 3 to splash them in water
Type 4 to run
What do you want to do?: 3
How do you want to do it?
Type 1 to use the hose
type 2 to use some random jars filled with water
Whats your pic?1
When you tern on the hose the pipes explode from under the vliagers and you knock them of there feet
The water puts out the fire
The villagers are running for you
What do you want to do?
Type 1 to run
Type 2 to eat a snack
Type 3 to do nothing
Traceback (most recent call last):
  File "C:\Users\JohnM\Downloads\downloadme\run.py", line 92, in <module>
    q23 = imput('Whats your pic?: ')
NameError: name 'imput' is not defined 
the error

**Comment by Nagol12344** [comment]
i fucked up some spelling, sorry about that
