### ISSUE TITLE
run does not work

### ISSUE THREAD

**Issue by Nagol12344** [Nagol12344/python-test#6]
Run (something you pick in game) is not working idk why

**Comment by Gamediamond3757** [comment]
run time pls

**Comment by Gamediamond3757** [comment]
the file name has a space in it remove the space to fix it

**Comment by Gamediamond3757** [comment]
look here https://github.com/Nagol12344/python-test/issues/7

**Comment by Gamediamond3757** [comment]
i am trying to help you

**Comment by Nagol12344** [comment]
its fixed so i can now close this
